### PR TITLE
implement https://github.com/thurstonsand/scala-cass/issues/4

### PR DESCRIPTION
**Pull request by holinov**
My try to implement #4

### CODE REVIEW

**Comment by thurstonsand** [comment]
this looks pretty good, but can you remove all of the formatting changes?

**Comment by thurstonsand** [comment]
also, i fixed some stuff related to the travis build, so if you merge in master, you should see tests actually run.

unfortunately...it seems like some difference between oracle jdk8 and openjdk8 is causing some sort of race condition in the test instance of cassandra. i need to address that, but for now, you may need to run the travis instances multiple times (by "restart job" option) to see if you can escape the race condition

**Comment by holinov** [comment]
1. about formatting - i'm intended to use corp-level style assistants and dissencouraged to use alternate (if it makes real trouble i'll try to switch to different PC)

1. about `this looks pretty good` -  it looks terrible (i event didn't get if my queries are cached cached as `prepeared`)

1. about travis - wtf? what do you mean me to do?

1. would it make sense if i'll implement Null/NonNull/ContainsIn in this kind of adt? it would be much easier if i'll have some ideas how this should be "used idiomatic way" )))

**Comment by thurstonsand** [comment]
1. im...surprised you cant just turn off styling for this particular project. 
   It makes it hard to understand what changes you've actually made, since there's so many no-op line changes. I just want to see the parts of code that you've modified/added.

2. looks like you modeled the code after what I did with `Nullable`, which seems about right.
you should model your test after [UpdateBehaviorTests](https://github.com/thurstonsand/scala-cass/blob/master/src/test/scala/com/weather/scalacass/UpdateBehaviorTests.scala) since that seems pretty self-contained

3. well, you merged master, so that's all i wanted you to do there about travis.
   you can see in the job [your test is failing](https://travis-ci.org/thurstonsand/scala-cass/jobs/590704410)

4. If I understand what you're asking, then yeah you should model this the same way that `Null` is done. which you pretty much have. like i said, it seems about right, but I'll take a closer look if you can remove all the random formatting changes

**Pull request closed without merging**
